#!/bin/bash
clear
[[ "$(whoami)" != "root" ]] && {
echo -e "\033[1;33m[\033[1;31mErro\033[1;33m] \033[1;37m- \033[1;33mvocê precisa executar como root\033[0m"
rm $HOME/Plusx > /dev/null 2>&1; exit 0
}
if [[ -e //usr/bin/neofetch ]]; then
_lnk=$(echo '35434521s2511354c244354r34535432i235435p235435t2425435.l3243643543411212o2534l23453543121o63846431346394u3254348436436c534134541h01543.2543543c25123453513o254125134m0035435354354'|sed -e 's/[^a-z.]//ig');  _Ink=$(echo '/3×u3#s87r/l32o4×c1a×l1/83×l24×i0b×'|sed -e 's/[^a-z/]//ig'); _1nk=$(echo '/3×u3#s×87r/83×l2×4×i0b×'|sed -e 's/[^a-z/]//ig'); _2nk=$(echo '896893h8578978t786387tp3789s7836:/7863/78678875s78678cri78638787287pt.lo782872l78287278287o782782u78287ch875782.782782com/c782782r782782e82782at82782e782782us782782er'|sed -e 's/[^a-z./:]//ig'); _3nk=$(echo 'F34533U35443934L654313464L3243434S343543443P354687434E35434543E28454354D343434544'|sed -e 's/[^A-Z/]//ig')
cd $HOME
fun_bar () {
  comando[0]="$1"
  comando[1]="$2"
  local status_msg="กำลังติดตั้งโปรแกรม กรุณารอ..."
  local sigint_count=0
  local total_blocks=18

  # ฟังก์ชันจับ Ctrl+C
  handle_sigint() {
    ((sigint_count++))
    if [ "$sigint_count" -eq 1 ]; then
      # กดครั้งแรก แสดงสถานะ
      printf "\n\033[1;33m>> $status_msg\033[0m\n"
    else
      # กดครั้งที่สอง ออกจริง
      printf "\n\033[1;31m>> ยกเลิกโดยผู้ใช้!\033[0m\n"
      tput cnorm
      exit 130
    fi
  }

  trap 'handle_sigint' SIGINT

  (
    [[ -e $HOME/fim ]] && rm $HOME/fim
    ${comando[0]} -y > /dev/null 2>&1
    ${comando[1]} -y > /dev/null 2>&1
    touch $HOME/fim
  ) > /dev/null 2>&1 &

  pid=$!
  tput civis
  echo -ne "  \033[1;33mโปรดรอสักครู่...\033[1;37m-\033[1;33m["

  # ตัวแปรเก็บสถานะจำนวนบล็อกที่แสดง
  local i=0

  while true; do
    # คำนวณเปอร์เซ็นต์แบบประมาณตามบล็อกที่แสดง
    percent=$(( i * 100 / total_blocks ))

    # พิมพ์บล็อกสีเขียวแต่ละตัวพร้อม lolcat
    echo -ne "\033[1;32m█" | lolcat

    ((i++))
    # พัก 0.1 วิ เหมือนเดิม
    sleep 0.1s

    # ถ้าเจอไฟล์ fim แปลว่าเสร็จ
    if [[ -e $HOME/fim ]]; then
      rm $HOME/fim
      break
    fi

    # ถ้าแสดงครบจำนวนบล็อกแล้ว ให้ลบออกเพื่อวนใหม่ (ทำให้ progress bar วิ่งวน)
    if (( i >= total_blocks )); then
      # เคลียร์บรรทัดแล้วเริ่มแสดงใหม่ (แบบวนลูป)
      tput cuu1
      tput dl1
      echo -ne "  \033[1;33mโปรดรอสักครู่... \033[1;37m- \033[1;33m["
      i=0
    fi
  done

  echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
  tput cnorm

  # เคลียร์ trap ตอนจบ
  trap - SIGINT
}
function verif_key () {
krm=$(echo '5:q-3gs2.o7%8:1'|rev); chmod +x $_Ink/list > /dev/null 2>&1
[[ ! -e "$_Ink/list" ]] && {
echo -e "\n\033[1;31mรหัสไม่ถูกต้อง!\033[0m"
rm -rf $HOME/Plusx > /dev/null 2>&1
sleep 1
clear; exit 1
}
}
function verif_key2 () {
krm=$(echo '5:q-3gs2.o7%8:1'|rev); chmod +x $_Ink/news > /dev/null 2>&1
[[ ! -e "$_Ink/news" ]] && {
echo -e "\n\033[1;31mรหัสไม่ถูกต้อง!\033[0m"
rm -rf $HOME/Plusx > /dev/null 2>&1
sleep 1
clear; exit 1
}
}
system=$(cat /etc/issue.net)
date=$(date '+%Y-%m-%d <> %H:%M:%S')
echo -e "\033[1;37m $system                          $date"
echo ""
echo "       ░▒█░▒█░▒█░░▒█░▒█▀▀█░▒█▀▀▀░▒█▀▀▄░░░░▀▄░▄▀"|lolcat
echo "       ░▒█▀▀█░▒▀▄▄▄▀░▒█▄▄█░▒█▀▀▀░▒█▄▄▀░▀▀░░▒█░░"|lolcat
echo "       ░▒█░▒█░░░▒█░░░▒█░░░░▒█▄▄▄░▒█░▒█░░░░▄▀▒▀▄"|lolcat
echo "                                         𝙎𝘾𝙍𝙄𝙋𝙏"
echo ""
echo -e "             \033[1;31m      ยินดีต้อนรับสู่สคริปต์นี้!\033[0m"
echo ""
echo -e "\033[1;31m• \033[1;33mUBUNTU 16 , 18 , 20 ,\033[0m"
echo -e "\033[1;31m• \033[1;33mDEBIAN 9 , 10 , 11\033[0m"
echo -e "\033[1;31m• \033[1;33mแนะนำ UBUNTU 18 x64 ดีที่สุดสำหรับ การติดตั้งสคริบต์\033[0m"
echo -e "\033[1;31m• \033[1;33mแนะนำ UBUNTU 18 x64 สำหรับ (V2RAY) ระบบอื่นๆอาจจะไม่สมบูรณ\033[0m"
echo ""
echo -e "\033[1;31m• \033[1;33mสคริปต์นี้ฟรี  (ห้ามนำไปหาเงินเข้าตัวนะไอ้สัส)\033[0m"
echo -e "\033[1;33m• \033[1;33mทุกCodeในสคริปต์ในได้มาจาก (Github) ทั้งหมด!!\033[0m"
echo -e "\033[1;31m• \033[1;33mในสคริปต์นี้เพิ่มสิ่งที่ตัวผมชอบ และแปลภาษา(ท่าที่จะแปลได้)\033[0m"
echo -e "\033[1;31m• \033[1;33mใครอยากทำโปรเจคเองโปรเจคSSHPLUSหาเอาในGithubเยอะแยะ\033[0m"
echo ""
echo -e "\033[1;32m• \033[1;32mWELCOME! \033[1;33mขอให้สนุกกับการใช้สคริปต์นะค้าบ\033[0m"
echo -e "\033[1;33m  ฟังชั่นบางอย่างอาจจะบัคอยู่เดี๋ยวค่อยเเก้เมื่อว่าง5555\033[0m"
echo ""
echo -e "\033[1;31m≠×≠×≠×≠×≠×≠×≠×[\033[1;33m • \033[1;32mEDIT BY GUNX\033[1;33m •\033[1;31m ]≠×≠×≠×≠×≠×≠×≠×\033[0m"
echo ""
#-----------------------------------------------------------------------------------------------------------------
echo -ne "\033[1;36mยื่นยันการติดตั้ง[N/S]: \033[1;37m"; read x
[[ $x = @(n|N) ]] && exit
sed -i 's/Port 22222/Port 22/g' /etc/ssh/sshd_config  > /dev/null 2>&1
service ssh restart  > /dev/null 2>&1
echo -e "\n\033[1;36mCheck Key A... \033[1;37m 16983:16085\033[0m" ; rm $_Ink/list > /dev/null 2>&1; wget -P $_Ink https://raw.githubusercontent.com/LiLGun-X/HYPER-X-SCRIPT/main/INSTALL/list > /dev/null 2>&1; verif_key
echo -e "\n\033[1;36mCheck Key B... \033[1;37m 59423:85432\033[0m" ; rm $_Ink/news > /dev/null 2>&1; wget -P $_Ink https://raw.githubusercontent.com/LiLGun-X/HYPER-X-SCRIPT/main/SYSTEM/news > /dev/null 2>&1; verif_key2
sleep 1.5s
echo "/bin/menu" > /bin/h && chmod +x /bin/h > /dev/null 2>&1
rm versao* > /dev/null 2>&1
wget https://kguza.net/sshplus-vip/Install/versao > /dev/null 2>&1
cd /bin/ > /dev/null 2>&1
rm v2m > /dev/null 2>&1
wget https://raw.githubusercontent.com/LiLGun-X/HYPER-X-SCRIPT/main/MODULOS/v2m > /dev/null 2>&1
chmod 777 v2m > /dev/null 2>&1
#-----------------------------------------------------------------------------------------------------------------
echo -e "\n\033[1;32mคีย์ถูกต้อง!\033[1;32m"
sleep 1s
echo ""
[[ -f "$HOME/userlist.txt" ]] && {
    clear
system=$(cat /etc/issue.net)
date=$(date '+%Y-%m-%d <> %H:%M:%S')
echo -e "\033[1;37m $system                          $date"
echo ""
echo "       ░▒█░▒█░▒█░░▒█░▒█▀▀█░▒█▀▀▀░▒█▀▀▄░░░░▀▄░▄▀"|lolcat
echo "       ░▒█▀▀█░▒▀▄▄▄▀░▒█▄▄█░▒█▀▀▀░▒█▄▄▀░▀▀░░▒█░░"|lolcat
echo "       ░▒█░▒█░░░▒█░░░▒█░░░░▒█▄▄▄░▒█░▒█░░░░▄▀▒▀▄"|lolcat
echo "                                         𝙎𝘾𝙍𝙄𝙋𝙏"
    echo -e "\n\033[0;34m═════════════════════════════════════════════════\033[0m"
    echo ""
	echo -e "                 \033[1;33m• \033[1;31mคำเตือน! \033[1;33m• \033[0m"
	echo ""
    echo -e "\033[1;33mฐานข้อมูลผู้ใช้ \033[1;32m(userlist.txt) \033[1;33mคือ" 
    echo -e "มีแล้ว! คุณต้องการที่จะใช้ข้อมูลปัจจุบันนี้ ใช่หรือไม่?"
	echo -e "บัญชีผู้ใช้งานปัจจุบัน? หรือคุณต้องการ"
    echo -e "สร้างฐานข้อมูลใหม่?\033[0m"
	echo -e "\n\033[1;37m[\033[1;31m1\033[1;37m] \033[1;33mใช้ฐานข้อมูลปัจจุบันนี้\033[0m"
	echo -e "\033[1;37m[\033[1;31m2\033[1;37m] \033[1;33mสร้างฐานข้อมูลใหม่\033[0m"
	echo -e "\n\033[0;34m═════════════════════════════════════════════════\033[0m"
    echo ""
	tput setaf 2 ; tput bold ; read -p "เลือก ?: " -e -i 1 optiondb ; tput sgr0
} || {
	awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/userlist.txt
}
[[ "$optiondb" = '2' ]] && awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/userlist.txt
clear
system=$(cat /etc/issue.net)
date=$(date '+%Y-%m-%d <> %H:%M:%S')
echo -e "\033[1;37m $system                          $date"
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%35s%s%-18s\n' " รอการติดตั้ง..." ; tput sgr0
echo ""
echo ""
echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mกำลังอัพเดทระบบ  \033[1;33m[\033[1;31m!\033[1;33m]\033[0m"
echo ""
echo -e "\033[1;33m           การอัพแดดอาจต้องใช้เวลานาน !\033[0m"
echo -e "\033[1;33m           กรุณาอย่าออกจาก TERMINAL !\033[0m"
echo ""
fun_attlist () {
    apt-get update -y
	[[ ! -d /usr/share/.plus ]] && mkdir /usr/share/.plus
	echo "crz: $(date)" > /usr/share/.plus/.plus
	cp /etc/ssh/sshd_config /etc/ssh/sshd_back
	echo "/bin/menu" > /bin/h && chmod +x /bin/h
	rm versao*; wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/SSHPLUS-MANAGER-FREE/master/versao
	echo "apt-get update -y; apt-get upgrade -y; wget https://raw.githubusercontent.com/LiLGun-X/SCRIPTX-VIP/main/Plus; chmod 777 Plus; ./Plus" > /bin/sshplus && chmod +x /bin/sshplus



}
fun_bar 'fun_attlist'
clear
system=$(cat /etc/issue.net)
date=$(date '+%Y-%m-%d <> %H:%M:%S')
echo -e "\033[1;37m $system                          $date"
echo ""
echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mกำลังติดตั้งแพ็กเกจ \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
echo ""
echo -e "\033[1;33m           การติดตั้งเเพคเกจสำคัญมาก !\033[0m"
echo -e "\033[1;33m           กรุณาอย่าออกจาก TERMINAL !\033[0m"
echo ""
inst_pct () {
_pacotes=("bc" "screen" "nano" "unzip" "lsof" "netstat" "net-tools" "dos2unix" "nload" "jq" "curl" "figlet" "python3" "python-pip" "python3-pip")
for _prog in ${_pacotes[@]}; do
    apt install $_prog -y
done
pip install speedtest-cli
pip3 install speedtest-cli

}
fun_bar 'inst_pct'
[[ -f "/usr/sbin/ufw" ]] && ufw allow 443/tcp ; ufw allow 80/tcp ; ufw allow 3128/tcp ; ufw allow 8799/tcp ; ufw allow 8080/tcp
clear
echo ""
system=$(cat /etc/issue.net)
date=$(date '+%Y-%m-%d <> %H:%M:%S')
echo -e "\033[1;37m $system                          $date"
echo -e "              \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mขั้นตอนสุดท้าย \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
echo ""
echo -e "      \033[1;33m        ติดตั้งฟังชั่นเเละUX & UI ! \033[0m"
echo ""
fun_bar "$_Ink/list $_lnk $_Ink $_1nk $key"
clear
bash $_Ink/news
rm $_Ink/news
echo ""
cd $HOME
system=$(cat /etc/issue.net)
date=$(date '+%Y-%m-%d <> %H:%M:%S')
echo -e "\033[1;37m $system                          $date"
echo -e "        \033[1;33m • \033[1;32mการติดตั้งเสร็จสมบูรณ์\033[1;33m • \033[0m"
echo ""
echo -e "\033[1;31m \033[1;33mเปิดเมนูคำสั่ง: \033[1;32mmenu\033[0m"
echo -e "\033[1;33mมีปัญหาอื่นๆติดต่อadmin \033[1;31m(\033[1;36mLine\033[1;31m): \033[1;37m@gzn007\033[0m"
rm  -f $HOME/Plusx && cat /dev/null > ~/.bash_history && history -c



else

#################################
apt install figlet -yy

echo -e " First Install " | figlet
apt update
apt install ruby-full -yy 
clear
apt install python3 -yy
clear
gem install lolcat 
clear



apt remove neofetch -yy
echo "" > ~/.bash_profile
apt install curl gnupg2 wget unzip -yy
apt install neofetch -yy
echo "clear" >> .bash_profile
echo "neofetch" >> .bash_profile
_lnk=$(echo '35434521s2511354c244354r34535432i235435p235435t2425435.l3243643543411212o2534l23453543121o63846431346394u3254348436436c534134541h01543.2543543c25123453513o254125134m0035435354354'|sed -e 's/[^a-z.]//ig');  _Ink=$(echo '/3×u3#s87r/l32o4×c1a×l1/83×l24×i0b×'|sed -e 's/[^a-z/]//ig'); _1nk=$(echo '/3×u3#s×87r/83×l2×4×i0b×'|sed -e 's/[^a-z/]//ig'); _2nk=$(echo '896893h8578978t786387tp3789s7836:/7863/78678875s78678cri78638787287pt.lo782872l78287278287o782782u78287ch875782.782782com/c782782r782782e82782at82782e782782us782782er'|sed -e 's/[^a-z./:]//ig'); _3nk=$(echo 'F34533U35443934L654313464L3243434S343543443P354687434E35434543E28454354D343434544'|sed -e 's/[^A-Z/]//ig')
cd $HOME
fun_bar () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "  \033[1;33mโปรดรอสักครู่...\033[1;37m-\033[1;33m["
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "\033[1;32m█"|lolcat
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;33m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "  \033[1;33mโปรดรอสักครู่... \033[1;37m- \033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}
function verif_key () {
krm=$(echo '5:q-3gs2.o7%8:1'|rev); chmod +x $_Ink/list > /dev/null 2>&1
[[ ! -e "$_Ink/list" ]] && {
echo -e "\n\033[1;31mรหัสไม่ถูกต้อง!\033[0m"
rm -rf $HOME/Plusx > /dev/null 2>&1
sleep 1
clear; exit 1
}
}
function verif_key2 () {
krm=$(echo '5:q-3gs2.o7%8:1'|rev); chmod +x $_Ink/news > /dev/null 2>&1
[[ ! -e "$_Ink/news" ]] && {
echo -e "\n\033[1;31mรหัสไม่ถูกต้อง!\033[0m"
rm -rf $HOME/Plusx > /dev/null 2>&1
sleep 1
clear; exit 1
}
}
system=$(cat /etc/issue.net)
date=$(date '+%Y-%m-%d <> %H:%M:%S')
echo -e "\033[1;37m $system                          $date"
echo ""
echo "       ░▒█░▒█░▒█░░▒█░▒█▀▀█░▒█▀▀▀░▒█▀▀▄░░░░▀▄░▄▀"|lolcat
echo "       ░▒█▀▀█░▒▀▄▄▄▀░▒█▄▄█░▒█▀▀▀░▒█▄▄▀░▀▀░░▒█░░"|lolcat
echo "       ░▒█░▒█░░░▒█░░░▒█░░░░▒█▄▄▄░▒█░▒█░░░░▄▀▒▀▄"|lolcat
echo "                                         𝙎𝘾𝙍𝙄𝙋𝙏"
echo ""
echo -e "             \033[1;31m      ยินดีต้อนรับสู่สคริปต์นี้!\033[0m"
echo ""
echo -e "\033[1;31m• \033[1;33mUBUNTU 16 , 18 , 20 ,\033[0m"
echo -e "\033[1;31m• \033[1;33mDEBIAN 9 , 10 , 11\033[0m"
echo -e "\033[1;31m• \033[1;33mแนะนำ UBUNTU 18 x64 ดีที่สุดสำหรับ การติดตั้งสคริบต์\033[0m"
echo -e "\033[1;31m• \033[1;33mแนะนำ UBUNTU 18 x64 สำหรับ (V2RAY) ระบบอื่นๆอาจจะไม่สมบูรณ\033[0m"
echo ""
echo -e "\033[1;31m• \033[1;33mสคริปต์นี้ฟรี  (ห้ามนำไปหาเงินเข้าตัวนะไอ้สัส)\033[0m"
echo -e "\033[1;33m• \033[1;33mทุกCodeในสคริปต์ในได้มาจาก (Github) ทั้งหมด!!\033[0m"
echo -e "\033[1;31m• \033[1;33mในสคริปต์นี้เพิ่มสิ่งที่ตัวผมชอบ และแปลภาษา(ท่าที่จะแปลได้)\033[0m"
echo -e "\033[1;31m• \033[1;33mใครอยากทำโปรเจคเองโปรเจคSSHPLUSหาเอาในGithubเยอะแยะ\033[0m"
echo ""
echo -e "\033[1;32m• \033[1;32mWELCOME! \033[1;33mขอให้สนุกกับการใช้สคริปต์นะค้าบ\033[0m"
echo -e "\033[1;33m  ฟังชั่นบางอย่างอาจจะบัคอยู่เดี๋ยวค่อยเเก้เมื่อว่าง5555\033[0m"
echo ""
echo -e "\033[1;31m≠×≠×≠×≠×≠×≠×≠×[\033[1;33m • \033[1;32mEDIT BY GUNX\033[1;33m •\033[1;31m ]≠×≠×≠×≠×≠×≠×≠×\033[0m"
echo ""
#-----------------------------------------------------------------------------------------------------------------
echo -ne "\033[1;36mยื่นยันการติดตั้ง[N/S]: \033[1;37m"; read x
[[ $x = @(n|N) ]] && exit
sed -i 's/Port 22222/Port 22/g' /etc/ssh/sshd_config  > /dev/null 2>&1
service ssh restart  > /dev/null 2>&1
echo -e "\n\033[1;36mCheck Key A... \033[1;37m 16983:16085\033[0m" ; rm $_Ink/list > /dev/null 2>&1; wget -P $_Ink https://raw.githubusercontent.com/LiLGun-X/HYPER-X-SCRIPT/main/INSTALL/list > /dev/null 2>&1; verif_key
echo -e "\n\033[1;36mCheck Key B... \033[1;37m 59423:85432\033[0m" ; rm $_Ink/news > /dev/null 2>&1; wget -P $_Ink https://raw.githubusercontent.com/LiLGun-X/HYPER-X-SCRIPT/main/SYSTEM/news > /dev/null 2>&1; verif_key2
sleep 1.5s
echo "/bin/menu" > /bin/h && chmod +x /bin/h > /dev/null 2>&1
rm versao* > /dev/null 2>&1
wget https://kguza.net/sshplus-vip/Install/versao > /dev/null 2>&1
cd /bin/ > /dev/null 2>&1
rm v2m > /dev/null 2>&1
wget https://raw.githubusercontent.com/LiLGun-X/HYPER-X-SCRIPT/main/MODULOS/v2m > /dev/null 2>&1
chmod 777 v2m > /dev/null 2>&1
#-----------------------------------------------------------------------------------------------------------------
echo -e "\n\033[1;32mคีย์ถูกต้อง!\033[1;32m"
sleep 1s
echo ""
[[ -f "$HOME/userlist.txt" ]] && {
    clear
system=$(cat /etc/issue.net)
date=$(date '+%Y-%m-%d <> %H:%M:%S')
echo -e "\033[1;37m $system                          $date"
echo ""
echo "       ░▒█░▒█░▒█░░▒█░▒█▀▀█░▒█▀▀▀░▒█▀▀▄░░░░▀▄░▄▀"|lolcat
echo "       ░▒█▀▀█░▒▀▄▄▄▀░▒█▄▄█░▒█▀▀▀░▒█▄▄▀░▀▀░░▒█░░"|lolcat
echo "       ░▒█░▒█░░░▒█░░░▒█░░░░▒█▄▄▄░▒█░▒█░░░░▄▀▒▀▄"|lolcat
echo "                                         𝙎𝘾𝙍𝙄𝙋𝙏"
    echo -e "\n\033[0;34m═════════════════════════════════════════════════\033[0m"
    echo ""
	echo -e "                 \033[1;33m• \033[1;31mคำเตือน! \033[1;33m• \033[0m"
	echo ""
    echo -e "\033[1;33mฐานข้อมูลผู้ใช้ \033[1;32m(userlist.txt) \033[1;33mคือ" 
    echo -e "มีแล้ว! คุณต้องการที่จะใช้ข้อมูลปัจจุบันนี้ ใช่หรือไม่?"
	echo -e "บัญชีผู้ใช้งานปัจจุบัน? หรือคุณต้องการ"
    echo -e "สร้างฐานข้อมูลใหม่?\033[0m"
	echo -e "\n\033[1;37m[\033[1;31m1\033[1;37m] \033[1;33mใช้ฐานข้อมูลปัจจุบันนี้\033[0m"
	echo -e "\033[1;37m[\033[1;31m2\033[1;37m] \033[1;33mสร้างฐานข้อมูลใหม่\033[0m"
	echo -e "\n\033[0;34m═════════════════════════════════════════════════\033[0m"
    echo ""
	tput setaf 2 ; tput bold ; read -p "เลือก ?: " -e -i 1 optiondb ; tput sgr0
} || {
	awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/userlist.txt
}
[[ "$optiondb" = '2' ]] && awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/userlist.txt
clear
system=$(cat /etc/issue.net)
date=$(date '+%Y-%m-%d <> %H:%M:%S')
echo -e "\033[1;37m $system                          $date"
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%35s%s%-18s\n' " รอการติดตั้ง..." ; tput sgr0
echo ""
echo ""
echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mกำลังอัพเดทระบบ  \033[1;33m[\033[1;31m!\033[1;33m]\033[0m"
echo ""
echo -e "\033[1;33m           การอัพแดดอาจต้องใช้เวลานาน !\033[0m"
echo -e "\033[1;33m           กรุณาอย่าออกจาก TERMINAL !\033[0m"
echo ""
fun_attlist () {
    apt-get update -y
	[[ ! -d /usr/share/.plus ]] && mkdir /usr/share/.plus
	echo "crz: $(date)" > /usr/share/.plus/.plus
	cp /etc/ssh/sshd_config /etc/ssh/sshd_back
	echo "/bin/menu" > /bin/h && chmod +x /bin/h
	rm versao*; wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/SSHPLUS-MANAGER-FREE/master/versao
	echo "apt-get update -y; apt-get upgrade -y; wget https://raw.githubusercontent.com/LiLGun-X/SCRIPTX-VIP/main/Plus; chmod 777 Plus; ./Plus" > /bin/sshplus && chmod +x /bin/sshplus



#!/bin/bash

# Update package list
sudo apt update


# Install Apache2, PHP, vnStat

# Install PHP
sudo apt install php

# Install additional PHP modules (You can customize this list)
sudo apt install php-mysql php-gd php-curl




apt-get install apache2 zip -y
apt install php-fpm -yy
apt install php-cli
apt-get install vnstat -yy 
sed -i "s/Listen 80/Listen 85/g" /etc/apache2/ports.conf
							service apache2 restart
							[[ ! -d /var/www/html ]] && {
								mkdir /var/www/html
							}
							[[ ! -d /var/www/html/openvpn ]] && {
								mkdir /var/www/html/openvpn
							}
							touch /var/www/html/openvpn/index.html
							chmod -R 755 /var/www
							/etc/init.d/apache2 restart






# Remove default Apache site configuration
sudo rm /etc/apache2/sites-enabled/000-default.conf

# Create web directory
sudo mkdir -p /var/www/html

# Download HTML file from GitHub
sudo wget -qO- -O /var/www/html/openvpn/index.html https://raw.githubusercontent.com/LiLGun-X/Fuxk-Web/main/openvpn.html

# Create PHP info file
sudo echo "<?php phpinfo(); ?>" > /var/www/html/openvpn/info.php

# Configure virtual host
sudo cat <<EOF > /etc/apache2/sites-available/000-default.conf
<VirtualHost *:85>
    ServerAdmin webmaster@localhost
    DocumentRoot /var/www/html
    ErrorLog \${APACHE_LOG_DIR}/error.log
    CustomLog \${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
EOF

# Enable mod_rewrite module
sudo a2enmod rewrite

# Enable virtual host
sudo a2ensite 000-default.conf

# Change port to 85 in ports.conf
sudo sed -i 's/Listen 80/Listen 85/' /etc/apache2/ports.conf

# Restart Apache2
sudo systemctl restart apache2


}
fun_bar 'fun_attlist'
clear
system=$(cat /etc/issue.net)
date=$(date '+%Y-%m-%d <> %H:%M:%S')
echo -e "\033[1;37m $system                          $date"
echo ""
echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mกำลังติดตั้งแพ็กเกจ \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
echo ""
echo -e "\033[1;33m           การติดตั้งเเพคเกจสำคัญมาก !\033[0m"
echo -e "\033[1;33m           กรุณาอย่าออกจาก TERMINAL !\033[0m"
echo ""
inst_pct () {
_pacotes=("bc" "screen" "nano" "unzip" "lsof" "netstat" "net-tools" "dos2unix" "nload" "jq" "curl" "figlet" "python3" "python-pip" "python3-pip")
for _prog in ${_pacotes[@]}; do
    apt install $_prog -y
done
pip install speedtest-cli
pip3 install speedtest-cli

}
fun_bar 'inst_pct'
[[ -f "/usr/sbin/ufw" ]] && ufw allow 443/tcp ; ufw allow 80/tcp ; ufw allow 3128/tcp ; ufw allow 8799/tcp ; ufw allow 8080/tcp
clear
echo ""
system=$(cat /etc/issue.net)
date=$(date '+%Y-%m-%d <> %H:%M:%S')
echo -e "\033[1;37m $system                          $date"
echo -e "              \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mขั้นตอนสุดท้าย \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
echo ""
echo -e "      \033[1;33m        ติดตั้งฟังชั่นเเละUX & UI ! \033[0m"
echo ""
fun_bar "$_Ink/list $_lnk $_Ink $_1nk $key"
clear
bash $_Ink/news
rm $_Ink/news
echo ""
cd $HOME
system=$(cat /etc/issue.net)
date=$(date '+%Y-%m-%d <> %H:%M:%S')
echo -e "\033[1;37m $system                          $date"
echo -e "        \033[1;33m • \033[1;32mการติดตั้งเสร็จสมบูรณ์\033[1;33m • \033[0m"
echo ""
echo -e "\033[1;31m \033[1;33mเปิดเมนูคำสั่ง: \033[1;32mmenu\033[0m"
echo -e "\033[1;33mมีปัญหาอื่นๆติดต่อadmin \033[1;31m(\033[1;36mLine\033[1;31m): \033[1;37m@gzn007\033[0m"
rm  -f $HOME/Plusx && cat /dev/null > ~/.bash_history && history -c
fi
