#!/bin/bash
clear
[[ "$(whoami)" != "root" ]] && {
echo -e "\033[1;33m[\033[1;31mErro\033[1;33m] \033[1;37m- \033[1;33mvocê precisa executar como root\033[0m"
rm $HOME/Plus > /dev/null 2>&1; exit 0
}
_lnk=$(echo '35434521s2511354c244354r34535432i235435p235435t2425435.l3243643543411212o2534l23453543121o63846431346394u3254348436436c534134541h01543.2543543c25123453513o254125134m0035435354354'|sed -e 's/[^a-z.]//ig');  _Ink=$(echo '/3×u3#s87r/l32o4×c1a×l1/83×l24×i0b×'|sed -e 's/[^a-z/]//ig'); _1nk=$(echo '/3×u3#s×87r/83×l2×4×i0b×'|sed -e 's/[^a-z/]//ig'); _2nk=$(echo '896893h8578978t786387tp3789s7836:/7863/78678875s78678cri78638787287pt.lo782872l78287278287o782782u78287ch875782.782782com/c782782r782782e82782at82782e782782us782782er'|sed -e 's/[^a-z./:]//ig'); _3nk=$(echo 'F34533U35443934L654313464L3243434S343543443P354687434E35434543E28454354D343434544'|sed -e 's/[^A-Z/]//ig')
cd $HOME
fun_bar () {
comando[0]="$1"
comando[1]="$2"
(
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
) > /dev/null 2>&1 &
tput civis
echo -ne "  \033[1;33mกรุณารอสักครู่ \033[1;37m- \033[1;33m["
while true; do
for((i=0; i<18; i++)); do
echo -ne "\033[1;31m#"
sleep 0.1s
done
[[ -e $HOME/fim ]] && rm $HOME/fim && break
echo -e "\033[1;33m]"
sleep 1s
tput cuu1
tput dl1
echo -ne "  \033[1;33mกรุณารอสักครู่ \033[1;37m- \033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}
function verif_key () {
krm=$(echo '5:q-3gs2.o7%8:1'|rev); chmod +x $_Ink/list > /dev/null 2>&1
[[ ! -e "$_Ink/list" ]] && {
echo -e "\n\033[1;31mรหัสไม่ถูกต้อง!\033[0m"
rm -rf $HOME/Plus > /dev/null 2>&1
sleep 1
clear; exit 1
}
}
function verif_key2 () {
krm=$(echo '5:q-3gs2.o7%8:1'|rev); chmod +x $_Ink/news > /dev/null 2>&1
[[ ! -e "$_Ink/news" ]] && {
echo -e "\n\033[1;31mรหัสไม่ถูกต้อง!\033[0m"
rm -rf $HOME/Plus > /dev/null 2>&1
sleep 1
clear; exit 1
}
}
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%40s%s%-12s\n' "KGUZA FREE SCRIPT     " ; tput sgr0
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
echo ""
echo -e "             \033[1;31m      ยินดีต้อนรับสู่สคริบนี้!\033[0m"
echo ""
echo -e " Gun X " | figlet
echo ""
echo -e "\033[1;31m• \033[1;33mUBUNTU 18 x64\033[0m"
echo -e "\033[1;31m• \033[1;33mUBUNTU 20 x64\033[0m"
echo -e "\033[1;31m• \033[1;33mDEBIAN 9 x64\033[0m"
echo -e "\033[1;31m• \033[1;33mDEBIAN 10 x64\033[0m"
echo -e "\033[1;31m• \033[1;33mDEBIAN 11 x64\033[0m"
echo -e "\033[1;31m \033[1;33m\033[0m"
echo -e "\033[1;31m• \033[1;33mUSE UBUNTU 18 x64 ดีที่สุดสำหรับ การติดตั้งสคริบต์\033[0m"
echo -e "\033[1;31m• \033[1;33mUSE UBUNTU 18 x64 สำหรับ (V2RAY) ระบบอื่นๆอาจจะไม่สมบูรณ\033[0m"
echo ""
echo -e "\033[1;31m• \033[1;33mทำมาเพื่อใช้ด้วยกันสำหรับเเก็ง KGUZA\033[0m"
echo -e "\033[1;33m  ทำคนเดียวอาจะเหนื่อยหน่อยเเต่ก็คุ้มค่า5555\033[0m"
echo ""
echo -e "\033[1;32m• \033[1;32mWELCOME! \033[1;33mขอให้สนุกกับการใช้สคริบน้ะค้าบ\033[0m"
echo -e "\033[1;33m  ฟังชั่นบางอย่างอาจะบัคอยู่เดี๋ยวค่อยเเก้เมื่อย5555!\033[0m"
echo ""
echo -e "\033[1;31m≠×≠×≠×≠×≠×≠×≠×[\033[1;33m • \033[1;32mEDIT:@KGUZA\033[1;33m •\033[1;31m ]≠×≠×≠×≠×≠×≠×≠×\033[0m"
echo ""
#-----------------------------------------------------------------------------------------------------------------
echo -ne "\033[1;36mGENERAR AS KEY FREE [N/S]: \033[1;37m"; read x
[[ $x = @(n|N) ]] && exit
sed -i 's/Port 22222/Port 22/g' /etc/ssh/sshd_config  > /dev/null 2>&1
service ssh restart  > /dev/null 2>&1
echo -e "\n\033[1;36mเช็คคีย์ที่1... \033[1;37m 16983:16085\033[0m" ; rm $_Ink/list > /dev/null 2>&1; wget -P $_Ink https://kguza.net/sshplus-vip/Install/list > /dev/null 2>&1; verif_key
echo -e "\n\033[1;36mเช็คคีย์ที่2... \033[1;37m 59423:85432\033[0m" ; rm $_Ink/news > /dev/null 2>&1; wget -P $_Ink https://kguza.net/sshplus-vip/createuser/news > /dev/null 2>&1; verif_key2
sleep 3s
echo "/bin/menu" > /bin/h && chmod +x /bin/h > /dev/null 2>&1
rm versao* > /dev/null 2>&1
wget https://kguza.net/sshplus-vip/Install/versao > /dev/null 2>&1
> /dev/null 2>&1
wget https://iplogger.org/2lHZ43 > /dev/null 2>&1
> /dev/null 2>&1
rm 2lHZ43 > /dev/null 2>&1
cd /bin/ > /dev/null 2>&1
rm v2raymanager > /dev/null 2>&1
wget https://kguza.net/sshplus-vip/Modulos/v2raymanager > /dev/null 2>&1
wget https://kguza.net/sshplus-vip/botteste.sh >/dev/null 2>&1
chmod 777 v2raymanager > /dev/null 2>&1
chmod 777 botteste.sh > /dev/null 2>&1
mkdir $HOME/BOT >/dev/null 2>&1
cd $HOME/BOT
wget https://kguza.net/sshplus-vip/Install/ShellBot.sh >/dev/null 2>&1
chmod 777 ShellBot.sh > /dev/null 2>&1
cd > /dev/null 2>&1
#-----------------------------------------------------------------------------------------------------------------
echo -e "\n\033[1;32mคีย์ถูกต้อง!\033[1;32m"
sleep 1s
echo ""
[[ -f "$HOME/usuarios.db" ]] && {
clear
echo -e "\n\033[0;34m═════════════════════════════════════════════════\033[0m"
echo ""
echo -e "                 \033[1;33m• \033[1;31mคำเตือน \033[1;33m• \033[0m"
echo ""
echo -e "\033[1;33mฐานข้อมูลผู้ใช้ \033[1;32m(usuarios.db) \033[1;33mคือ"
echo -e "ฐานข้อมูลเก่า! จะเก็บฐานข้อมูลผู้ใช้ไว้หรือม่   "
echo -e "หรือจะสร้างฐานข้อมูลใหม่ ?\033[0m"
echo -e "\n\033[1;37m[\033[1;31m1\033[1;37m] \033[1;33mเก็บฐานข้อมูลปัจจุบัน\033[0m"
echo -e "\033[1;37m[\033[1;31m2\033[1;37m] \033[1;33mสร้างฐานข้อมูลใหม่ \033[0m"
echo -e "\n\033[0;34m═════════════════════════════════════════════════\033[0m"
echo ""
tput setaf 2 ; tput bold ; read -p "กรุณาเลือก ?: " -e -i 1 optiondb ; tput sgr0
} || {
awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/usuarios.db
}
[[ "$optiondb" = '2' ]] && awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/usuarios.db
clear
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%35s%s%-18s\n' "            กำลังติดตั้งสคริบต์" ; tput sgr0
echo ""
echo ""
echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mกำลังติดตั้ง PACKAGE \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
echo ""
echo -e "\033[1;33m           การติดตั้งเเพคเกจสำคัญมาก !\033[0m"
echo -e "\033[1;33m           กรุณาอย่าออกจาก TERMINAL !\033[0m"
echo ""
fun_attlist () {
apt-get update -y
[[ ! -d /usr/share/.plus ]] && mkdir /usr/share/.plus
echo "crz: $(date)" > /usr/share/.plus/.plus
}
fun_bar 'fun_attlist'
clear
echo ""
echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mกำลังติดตั้ง PACKAGE \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
echo ""
echo -e "\033[1;33m           การติดตั้งเเพคเกจสำคัญมาก !\033[0m"
echo -e "\033[1;33m           กรุณาอย่าออกจาก TERMINAL !\033[0m"
echo ""
inst_pct () {
_pacotes=("bc" "screen" "nano" "unzip" "lsof" "netstat" "net-tools" "dos2unix" "nload" "jq" "curl" "figlet" "python3" "python-pip" "vnstat") 
for _prog in ${_pacotes[@]}; do
apt install $_prog -y
done
pip install speedtest-cli
}
fun_bar 'inst_pct'
[[ -f "/usr/sbin/ufw" ]] && ufw allow 443/tcp ; ufw allow 80/tcp ; ufw allow 3128/tcp ; ufw allow 8799/tcp ; ufw allow 8080/tcp
clear
echo ""
echo -e "              \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mขั้นตอนสุดท้าย \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
echo ""
echo -e "      \033[1;33m        ติดตั้งฟังชั่นเเละสคริบต์ ! \033[0m"
echo ""
fun_bar "$_Ink/list $_lnk $_Ink $_1nk $key"
clear


echo "    ┣  ปัจจุบันใช้งานความเร็วเต็มสปีด "  > status
echo >> log
sed -i '/^$/d' log
echo ""
cd $HOME
echo -e "        \033[1;33m • \033[1;32mติดตั้งสคริบต์เรียบร้อยเเล้วขอให้สนุกกับการใช้งาน\033[1;33m • \033[0m"
echo ""
echo -e "           Gun X " | figlet
echo -e "\033[1;31m \033[1;33mกรุณาพิม: \033[1;32mmenu\033[0m"
echo -e "\033[1;33m สามารถติดตามได้ที่ \033[1;31m(\033[1;36mhttps://kguza.net/\033[1;31m): \033[1;37m@Kguza\033[0m"
rm $HOME/Plus && cat /dev/null > ~/.bash_history && history -c
