#!/bin/bash
# install python
 apt install python3 -yy
apt update 
apt install ruby-full -yy 
gem install lolcat
apt -y install lolcat
apt -y install figlet 
apt -y install dos2unix 
rm -f setup.sh
rm -f screenfetch

cd /bin/bash /etc/openvpn
rm -f .profile
# Running screenfetch

sudo apt install neofetch -yy

apt-get install vnstat -yy 
systemctl start vnstat.service 


 
 echo "/bin/bash /etc/openvpn/openvpn.bash" >> .profile
 echo "clear" >> .profile
 echo "neofetch" >> .profile

scrip="https://raw.githubusercontent.com/tokssa/SAVAT/master"
clear
cd /usr/bin
wget -q -O cr "https://raw.githubusercontent.com/LiLGun-X/HYPER-X-SCRIPT/main/INSTALL/cr"
chmod +x /usr/bin/cr
if [[ $(id -g) != "0" ]] ; then
    echo ""
    echo "Script : สั่งรูทคำสั่ง [ sudo -i ] ก่อนรันสคริปนี้  "
    echo ""
    exit
fi
zenon=$2

if [[  ! -e /dev/net/tun ]] ; then
    echo "Script : TUN/TAP device is not available."
fi
cd
if [[ -e /etc/debian_version ]]; then
VERSION_ID=$(cat /etc/os-release | grep "VERSION_ID")
fi
if [[ -e /etc/yum ]]; then
VERSION_ID=$(cat /etc/os-release | grep "VERSION_ID")
fi
IP=$(wget -qO- ipv4.icanhazip.com);
if [[ $zenon == "" ]]
then
clear
cr
cd
clear
echo ""
echo "          ░▒█░▒█░▒█░░▒█░▒█▀▀█░▒█▀▀▀░▒█▀▀▄░░░░▀▄░▄▀"|lolcat
echo "          ░▒█▀▀█░▒▀▄▄▄▀░▒█▄▄█░▒█▀▀▀░▒█▄▄▀░▀▀░░▒█░░"|lolcat
echo "          ░▒█░▒█░░░▒█░░░▒█░░░░▒█▄▄▄░▒█░▒█░░░░▄▀▒▀▄"|lolcat
echo "                                            𝙎𝘾𝙍𝙄𝙋𝙏"
echo -e "\033[1;31m╔════════════════════════════════════════════════════════════╗\033[0m"
echo -e "\033[1;31m║ \E[5;34;47m                     Hyper-X-SCRIPT                       \E[0m \033[1;31m║"
echo -e "\033[1;31m╠════════════════════════════════════════════════════════════╣\033[0m"
echo -e "\033[1;31m║          \033[1;32mSCRIPT ใช้ติดตั้งOPENVPN & SSH & V2RAY\033[1;31m      ║"
echo -e "\033[1;31m║          \033[1;32mระบบและเวอร์ชั่นที่รองรับ Ubuntu18+ Debian 8+ \033[1;31m ║"
echo -e "\033[1;31m║          \033[1;32mติดต่อ-@Line gzn007\033[1;31m                      ║"
echo -e "\033[1;31m╠════════════════════════════════════════════════════════════╝\033[0m"
echo -ne "\033[1;31m╚═══{ \033[1;32mใส่รหัสผ่าน\033[1;31m}════┫"; read P
wget -q -O /usr/bin/pass https://raw.githubusercontent.com/Lil-Gun-X/HYPER-X-SCRIPT/main/Modulos/pass.txt
if ! grep -w -q $P /usr/bin/pass; then
clear
echo ""
echo ""
echo -e "\033[1;31m╔═════════════════════════════════════════════════════╗\033[0m"
echo -e "\033[1;31m║ \E[5;34;47m                 รหัสผิดไอ้โง่                       \E[0m \033[1;31m║"
echo -e "\033[1;31m║ \E[5;34;47m               Line : gzn007                       \E[0m \033[1;31m║"
echo -e "\033[1;31m╠════════════════════════════════════════════════════╣\033[0m"
echo " เสียใจด้วย รหัสผิด ถ้าไม่มีรหัสติดต่อแอดมินฯ"
rm /usr/bin/pass
exit
fi
echo ""
echo "        ╭━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╮ 
        ┣ แน่ใจคุณต้องการรันระบบ OpenVPN    
        ┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╯   "
    read -p "        ╰━━ ( Y/n ) : " -e -i y Confirn
    if [[ "$Confirn" = "y" || "$Confirn" = "Y" ]]; then
wget -q -O install "https://raw.githubusercontent.com/LiLGun-X/HYPER-X-SCRIPT/main/INSTALL/install"
bash install
exit
elif [[ "$Confirn" = "n" || "$Confirn" = "N" ]]; then
clear
clear
wget -O install "https://raw.githubusercontent.com/tokssa/SAVAT/master/install"
bash install
