#!/bin/bash
if [[ -e /etc/debian_version ]]; then
VERSION_ID=$(cat /etc/os-release | grep "VERSION_ID")
fi

if [[ $1 == "" ]]
then
if [[ -e /etc/vnstat.conf ]]; then
	INTERFACE=`vnstat -m | head -n2 | awk '{print $1}'`
	TOTALBW=$(vnstat -i $INTERFACE --nick local | grep "total:" | awk '{print $8" "substr ($9, 1, 1)}')
fi

ON=0
OFF=0
while read ONOFF
do
	ACCOUNT="$(echo $ONOFF | cut -d: -f1)"
	ID="$(echo $ONOFF | grep -v nobody | cut -d: -f3)"
	ONLINE="$(cat /etc/openvpn/openvpn-status.log | grep -Eom 1 $ACCOUNT | grep -Eom 1 $ACCOUNT)"
	if [[ $ID -ge 1000 ]]; then
		if [[ -z $ONLINE ]]; then
			OFF=$((OFF+1))
		else
			ON=$((ON+1))
		fi
		fi
done < /etc/passwd


	

echo "
 ======================
  เช็ดแบนวิทที่ใช้งานทั้งหมด
 ======================
  1. รายชั่วโมง
  2. รายวัน
  3. รายสัปดาห์
  4. รายเดือน
  5. สิบวันก่อนหน้า
"
echo -e "  up/down ${GRAY}$TOTALBW${NC}${GRAY}B${NC}  |  กำลังเชื่อมต่อ ${GRAY}$ON${NC} บัญชี
"
read -p " Enter Number : " opcao
else
opcao=$1
fi
case $opcao in
  01 | 1 )
  clear
bwh
 ;;
 02 | 2 )
 clear
vnstat -d ;;
 03 | 3 )
 clear
 vnstat -w;;
 04 | 4 )
 clear
vnstat -m ;;
 05 | 5 )
 clear
vnstat -t ;;
esac
echo "
 =====================
  sakariya misayalong
 =====================
 
"
