#!/bin/bash

if [[ $1 == "" ]]
then
[[ -e /etc/cron.d/reboot ]] && ar=$(echo -e "\033[1;32m◉ ") || ar=$(echo -e "\033[1;31m○ ")
[[ -e /etc/cron.d/reboot ]] && tx=$(grep -c "10.8.0" /etc/cron.d/reboot) || _onop="0"
cr
echo " ┈╭━━━━━━━━━━━━━━━━━━━━━━╮ "
echo " ┈┣     สถานะAuto Reboot $ar Test $tx   "
echo " ┈╰━┳━━━━━┳━━━━━━━━━━━━━━╯ "
echo " ┈╭━┻━━━━━┻━━━━━━━━━━━━━━╮ "
echo " ┈┣  🕰🕰 ตั้งเวลา Restart vps 🕰🕰 "
echo " ┈╰━┳━━━━━┳━━━━━━━━━━━━━━╯ "
echo " ┈╭━┻━━━━━┻━━━━━━━━━━━━━━╮ "
echo " ┈┣  🕰 1. ทุกวัน เวลา ตีหนึ่ง "
echo " ┈┣━━━━━━━━━━━━━━┫"
echo " ┈┣  🕰 2. ทุกๆ 07 วัน. "
echo " ┈┣━━━━━━━━━━━━━━┫"
echo " ┈┣  🕰 3. ทุกๆ 01 เดือน. "
echo " ┈┣━━━━━━━━━━━━━━┫"
echo " ┈┣  🕰 4. กำหมดค่าเอง "
echo " ┈┣━━━━━━━━━━━━━━┫"
echo " ┈┣  🕰 5. ปิดใช้งานรีบูตอัตโนมัตร "
echo " ┈╰━━━━━━━━━━━━━━━━━━━━━━╯"
echo " "
read -p " ┈┣  พิมพ์เลือก : " opcao
else
opcao=$1
fi
case $opcao in
  01 | 1 )
  echo " 00 1 * * * root /sbin/reboot" > /etc/cron.d/reboot
clear

echo " ┈╭━━━━━━━━━━━━━━━━━━━━━━╮ "
echo " ┈┣  🕰 ตั้งเวลา Restart vps 🕰 "
echo " ┈╰━━━━━━━┳━━━━━┳━━━━━━━━╯ "
echo " ┈╭━━━━━━━┻━━━━━┻━━━━━━━━╮ "
echo " ┈┣  🕰 ทุกวันเวลาตีหนึ่งเรียบร้อยแล้ว 🕰 "
echo " ┈╰━━━━━━━━━━━━━━━━━━━━━━╯ "
sleep 2.5s
service cron restart;;
  02 | 2 )
  echo " 0 0 * * 0 root /sbin/reboot" > /etc/cron.d/reboot
clear

echo " ┈╭━━━━━━━━━━━━━━━━━━━━━━╮ "
echo " ┈┣  🕰 ตั้งเวลา Restart vps 🕰 "
echo " ┈╰━━━━━━━┳━━━━━┳━━━━━━━━╯ "
echo " ┈╭━━━━━━━┻━━━━━┻━━━━━━━━╮ "
echo " ┈┣  🕰 ทุกๆ 7 วัน เรียบร้อยแล้ว 🕰 "
echo " ┈╰━━━━━━━━━━━━━━━━━━━━━━╯ "
sleep 2.5s
service cron restart;;
  03 | 3 )
  echo " 0 0 1 * * root /sbin/reboot" > /etc/cron.d/reboot
clear

echo " ┈╭━━━━━━━━━━━━━━━━━━━━━━╮ "
echo " ┈┣  🕰 ตั้งเวลา Restart vps 🕰 "
echo " ┈╰━━━━━━━┳━━━━━┳━━━━━━━━╯ "
echo " ┈╭━━━━━━━┻━━━━━┻━━━━━━━━╮ "
echo " ┈┣  🕰 ทุก 1 เดือน เรียบร้อยแล้ว 🕰 "
echo " ┈╰━━━━━━━━━━━━━━━━━━━━━━╯ "
sleep 2.5s
service cron restart;;
  04 | 4 )
clear
  echo " "
  echo " ┈╭━━━━━━━━━━━━━━━━━━━━━━╮ "
echo " ┈┣  🕰🕰 ตัวอย่างการตั้งค่า 🕰🕰 "
echo " ┈╰━━━━━━━┳━━━━━┳━━━━━━━━╯ "
echo " ┈╭━━━━━━━┻━━━━━┻━━━━━━━━╮ "
echo " ┈┣  🕰 0 * * * *   คือ 1ชม "
echo " ┈┣━━━━━━━━━━━━━━━━┫"
echo " ┈┣  🕰 0 */6 * * * คือ 6ชม "
echo " ┈┣━━━━━━━━━━━━━━━━┫"
echo " ┈┣  🕰 30 3 * * *  คือ ทุกวัน เวลา ตีสามครึ่ง "
echo " ┈┣━━━━━━━━━━━━━━━━┫"
echo " ┈┣  🕰 0 0 * * 0   คือ 7วัน "
echo " ┈┣━━━━━━━━━━━━━━━━┫"
echo " ┈┣  🕰 0 0 1 * *   คือ 1เดือน "
echo " ┈╰━━━━━━━━━━━━━━━━━━━━━━╯"
  
read -p " Time ( 0 0 * * 0 ) : " Set
echo "$Set root /sbin/reboot" > /etc/cron.d/reboot
echo " ┈╭━━━━━━━━━━━━━━━━━━━━━━╮ "
echo " ┈┣  🕰 ตั้งเวลา Restart vps 🕰 "
echo " ┈╰━━━━━━━┳━━━━━┳━━━━━━━━╯ "
echo " ┈╭━━━━━━━┻━━━━━┻━━━━━━━━╮ "
echo " ┈┣  🕰 ตั้งเลงาตามกำหนด เรียบร้อยแล้ว 🕰 "
echo " ┈╰━━━━━━━━━━━━━━━━━━━━━━╯ "
sleep 2.5s
service cron restart
echo -e "";;
 05 | 5 )
rm -f /etc/cron.d/reboot
clear
echo " ┈╭━━━━━━━━━━━━━━━━━━━━━━╮ "
echo " ┈┣  🕰 ปิด Restart vps เรียบร้อยแล้ว 🕰 "
echo " ┈╰━━━━━━━━━━━━━━━━━━━━━━╯ "
sleep 2.5s
service cron restart
echo -e " ";;
esac
