#!/bin/bash

echo -e "\E[44;1;37m             AUTO REBOOT              \E[0m"
echo -e "TEST"
echo -ne "\033[1;31m╰━━━━━━━━❪\033[1;32mESCOLHA OPÇÃO DESEJADA\033[1;33m\033[1;31m\033[1;37m : ";
read xi
tput cnorm
clear
case $xi in
1 | 01)
echo -e "\033[1;31M ESCOLHA UM HORÁRIO PARA O DESLIGAMENTO EX: \033[1;33m00:00 \033[1;32\033[0m"
echo -ne "\033[1;32mDIGITE A HORA \033[1;33m\033[1;37m: "
            read escolha
                echo ""
                echo -e "\033[1;31m HORÁRIO VÁLIDO!"
                sleep 4
                clear
   shutdown -r +$escolha
   echo " $escolha" > /etc/timeboot/v1
;;
