#!/bin/bash

#!/bin/bash

if [[ $1 == "" ]]
then
[[ -e /etc/cron.d/reboot ]] && ar=$(echo -e "\033[1;32m◉ ") || ar=$(echo -e "\033[1;31m○ ")
tx=$(cat /etc/cron.d/v2)
cr
echo -e "\E[44;1;37m             AUTO REBOOT              \E[0m"
echo -e "TEST"
echo -e "TEST"
echo -e "TEST"
echo " ┈╭━━━━━━━━━━━━━━━━━━━━━━╮ "
echo " ┈┣     สถานะAuto Reboot $ar Test $tx   "
echo " ┈╰━┳━━━━━┳━━━━━━━━━━━━━━╯ "
echo " "
read -p " ┈┣  พิมพ์เลือก : " opcao
else
opcao=$1
fi
case $opcao in

 1)
clear
   echo -e "\E[44;1;37m             AUTO REBOOT              \E[0m"
                                echo -e "\033[1;31mESSA FUNÇÃO ATIVA REINICIALIZAÇÃO AUTOMÁTICA DA TUA VPS \033[1;33m \033[1;32\033[0m"
   echo -e "\033[1;31M ESCOLHA UM HORÁRIO PARA O DESLIGAMENTO EX: \033[1;33m00:00 \033[1;32\033[0m"
echo -ne "\033[1;32mDIGITE A HORA \033[1;33m\033[1;37m: "
            read escolha
                echo ""
                echo -e "\033[1;31m HORÁRIO VÁLIDO!"
                sleep 4
                clear
   shutdown -r +$escolha
   echo -e ""
   echo -e "\033[1;33mAUTO REBOOT AS $escolha ATIVADO COM SUCESSO \033[0m"
   echo -e ""
   echo -e "\033[1;34m[\033[1;37m01 •\033[1;34m]\033[1;37m > \033[1;33mDESATIVAR REBOOT \033[1;37m\033[0;32m"
   echo -e ""
   echo -ne "\n\033[1;33mENTER \033[1;33mPARA VOLTAR AO \033[1;33mMENU!\033[0m"; read
   ;;
   1)
   clear
   echo -e "\E[44;1;37m             AUTO REBOOT              \E[0m"
   echo -e "\033[1;31mESSA FUNÇÃO DESATIVA A REINICIALIZAÇÃO AUTOMÁTICA DA TUA VPS \033[1;33m \033[1;32\033[0m"
   echo -e "\033[1;31mO HORÁRIO PRÉ DEFINIDO $escolha SERÁ DESATIVADO \033[1;33m \033[1;32\033[0m"
   shutdown -c
echo -e "\033[1;33mAUTO REBOOT DESATIVADO COM SUCESSO \033[0m"
echo -e ""
   echo -ne "\n\033[1;33mENTER \033[1;33mPARA VOLTAR AO \033[1;33mMENU!\033[0m"; read
   ;;

