#!/bin/bash

echo -e "\E[44;1;37m             AUTO REBOOT              \E[0m"
echo -e "TEST"
echo -ne "\033[1;31m╰━━━━━━━━❪\033[1;32mESCOLHA OPÇÃO DESEJADA\033[1;33m\033[1;31m\033[1;37m : ";
read xi
tput cnorm
clear
case $xi in
1 | 01)
fun_openssh
;;
