#!/bin/bash

STATUS="/etc/openvpn/openvpn-status.log"
while IFS= read -r line; do
    cols=($(echo "$line" | tr ',' ' '))
    
    if [[ ${#cols[@]} -eq 5 && ! $line =~ ^'Common Name' ]]; then
        cn=${cols[0]}
        recv=$(echo "${cols[2]}" | awk '{ printf "%.2f", $1 / (2^50) }')
        sent=$(echo "${cols[3]}" | awk '{ printf "%.2f", $1 / (2^50) }')
        connected_since=$(date -d @${cols[4]} +'%Y-%m-%d %H:%M:%S')
        hosts+=("$cn $recv $sent $connected_since")
    fi
    
    if [[ ${#cols[@]} -eq 4 && ! $line =~ ^'Virtual Address' ]]; then
        for h in "${hosts[@]}"; do
            h_cols=($h)
            if [[ ${h_cols[0]} == ${cols[1]} ]]; then
                virt=${cols[0]}
                h_cols+=("$virt")
                h="${h_cols[*]}"
            fi
        done
    fi
done < "$STATUS"

headers=("CLIENT" "CLIENT IP" "DOWNLOAD" "UPLOAD" "CONNECTED SINCE")
fmt="%-16s %-16s %14s %15s %19s\n"
printf "$fmt" "${headers[@]}"
for h in "${hosts[@]}"; do
    h_cols=($h)
    printf "$fmt" "${h_cols[@]}"
done
