#!/usr/bin/env python

STATUS = "/etc/openvpn/openvpn-status.log"
status_file = open(STATUS, 'r')
stats = status_file.readlines()
status_file.close()
hosts = []
headers = {  
    'cn':    'CLIENT', 
    'virt':  'CLIENT IP',
    'sent':  'DOWNLOAD', 
    'recv':  'UPLOAD',
    'time':  'CONNECTION TIME'
}
sizes = [  
    (1<<50, 'PB'),
    (1<<40, 'TB'),
    (1<<30, 'GB'),
    (1<<20, 'MB'),
    (1<<10, 'KB'),
    (1,     'B')
]

def byte2str(size):  
    for f, suf in sizes:
        if size >= f:
            break
    return "%.2f %s" % (size / float(f), suf)

for line in stats:  
    cols = line.split(',')
    if len(cols) == 5 and not line.startswith('Common Name'):
        host = {}
        host['cn'] = cols[0]
        host['recv'] = byte2str(int(cols[2]))
        host['sent'] = byte2str(int(cols[3]))
        host['start'] = cols[4].strip()  # Assuming start time is in the last column
        host['end'] = ""  # Initialize end time as an empty string
        hosts.append(host)
    if len(cols) == 4 and not line.startswith('Virtual Address'):
        for h in hosts:
            if h['cn'] == cols[1]:
                h['virt'] = cols[0]
                h['end'] = cols[3].strip()  # Assuming end time is in the last column

fmt = "   %(cn)-16s %(virt)-16s %(sent)14s %(recv)15s %(start)-18s %(end)-18s"
print(fmt % headers)
print("-" * 116)  # Add a separator line
print("\n".join([fmt % h for h in hosts]))
