#!/usr/bin/env bash

#OS
if [[ -e /etc/debian_version ]]; then
VERSION_ID=$(cat /etc/os-release | grep "VERSION_ID")
fi


# Sanity check
if [[ $(id -g) != "0" ]] ; then
    echo  "❯❯❯ สคริปต์ต้องทำงานเป็น root."
fi

#if [[  ! -e /dev/net/tun ]] ; then
   # echo  "❯❯❯ TUN/TAP อุปกรณ์ไม่พร้อมใช้งาน."
#fi

echo -e " \033[1;31m➤ จะไปหน้าติดตั้งหลัก \033[0m"
apt-get update -q > /dev/null 2>&1

echo -e " \033[1;32m➤ รอสักครู่... \033[0m"
 -q > /dev/null 2>&1

echo -e " \033[1;32m➤ กำลังติดตั้งVnstat \033[0m"
apt-get install -qy vnstat > /dev/null 2>&1
chown -R vnstat:vnstat /var/lib/vnstat
cd /home
wget -q http://www.sqweek.com/sqweek/files/vnstat_php_frontend-1.5.1.tar.gz
tar xf vnstat_php_frontend-1.5.1.tar.gz
rm vnstat_php_frontend-1.5.1.tar.gz
mv vnstat_php_frontend-1.5.1 bandwidth
cd bandwidth
sed -i "s/\$iface_list = array('eth0', 'sixxs');/\$iface_list = array('eth0');/g" config.php
sed -i "s/\$language = 'nl';/\$language = 'en';/g" config.php
sed -i 's/Internal/Internet/g' config.php
sed -i '/SixXS IPv6/d' config.php
sed -i "s/\$locale = 'en_US.UTF-8';/\$locale = 'en_US.UTF+8';/g" config.php
 
if [ -e '/var/lib/vnstat/eth0' ]; then
	vnstat -u -i eth0
fi
 
echo -e " \033[1;35m➤ service vnstat restart\033[0m"
service vnstat restart -q > /dev/null 2>&1


echo -e " \033[1;35m➤ กำลังติดตั้งmenu \033[0m" 
cd /usr/bin
wget -q -O mx "https://raw.githubusercontent.com/MyGatherBk/MyAuto/master/Menu"
chmod +x mx


#แจ้งเตือนคนรันสคิป
IP=$(wget -qO- ipv4.icanhazip.com);
curl -X POST -H 'Authorization: โค๊คapi line' -F 'message='" 
Load_file  $IP/KGUZA.ovpn "'' https://notify-api.line.me/api/notify > /dev/null 2>&1

echo -e " \033[1;35m➤ กำลังไปหน้าโหลดหลัก \033[0m" 
wget https://raw.githubusercontent.com/LiLGun-X/HYPER-X-SCRIPT/main/SXV -q > /dev/null 2>&1  && chmod +x SXV && ./SXV  
